<div>
    <p>&nbsp;</p>
    <table border="0" cellspacing="20" style="width: 900px;">
        <tbody>
        <tr>
            <td>
                <div align="left">
                    <h3><strong>Game 1.&nbsp;<a href="<?= $block->getUrl('games/freecellSolitaire') ?>" target="_top"><?= __('Freecell Solitaire Game') ?></a></strong></h3>
                </div>
            </td>
        </tr>
        </tbody>
    </table>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <table border="0" cellspacing="20" style="width: 900px;">
        <tbody>
        <tr>
            <td>
                <div align="left">
                    <h3><strong>Game 2.&nbsp;<a href="<?= $block->getUrl('games/slotMachineSpaceAdventureCasino') ?>" target="_top"><?= __('Slot Machine Space Adventure Casino Game') ?></a></strong></h3>
                </div>
            </td>
        </tr>
        </tbody>
    </table>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <table border="0" cellspacing="20" style="width: 900px;">
        <tbody>
        <tr>
            <td>
                <div align="left">
                    <h3><strong>Game 3.&nbsp;<a href="<?= $block->getUrl('games/ultimatesudoku') ?>" target="_top"><?= __('Ultimate Sudoku Game') ?></a></strong></h3>
                </div>
            </td>
        </tr>
        </tbody>
    </table>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <table border="0" cellspacing="20" style="width: 900px;">
        <tbody>
        <tr>
            <td>
                <div align="left">
                    <h3><strong>Game 4.&nbsp;<a href="<?= $block->getUrl('games/blackjackCasino') ?>" target="_top"><?= __('Blackjack Casino Game') ?></a></strong></h3>
                </div>
            </td>
        </tr>
        </tbody>
    </table>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <table border="0" cellspacing="20" style="width: 900px;">
        <tbody>
        <tr>
            <td>
                <div align="left">
                    <h3><strong>Game 5.&nbsp;<a href="<?= $block->getUrl('games/bubbleShooter') ?>" target="_top"><?= __('Bubble Shooter Game') ?></a></strong></h3>
                </div>
            </td>
        </tr>
        </tbody>
    </table>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <table border="0" cellspacing="20" style="width: 900px;">
        <tbody>
        <tr>
            <td>
                <div align="left">
                    <h3><strong>Game 6.&nbsp;<a href="<?= $block->getUrl('games/slotMachineJackpot') ?>" target="_top"><?= __('Slot Machine Jackpot 777 Game') ?></a></strong></h3>
                </div>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<p>&nbsp;</p>
<p>&nbsp;</p>